### ISSUE TITLE
Translator produces datatypes with incorrect long-names

### ISSUE THREAD

**Issue by agomezl** [CakeML/cakeml#552] opened 2018-11-13 21:24 UTC
This issue can be replicated in `translator/ml_translator_testScript.sml` with:

```sml
val _ = Datatype `my_type = my_case1 | my_case2 | my_case3`;

val _ = Datatype `my_dep_type = My_dep my_type`

val _ = ml_prog_update (open_module "My_module");
val r = register_type ``:my_type``;
val _ = ml_prog_update (close_module NONE);


val _ = ml_prog_update (open_module "My_module2");
val r = register_type ``:my_dep_type``;
val _ = ml_prog_update (close_module NONE);
```

this produces:

```sm
...
Dmod "My_module"
  [Dtype unknown_loc
     [([],"ml_translator_test_my_type",
       [("My_case3",[]); ("My_case2",[]); ("My_case1",[])])]];
Dmod "My_module2"
  [Dtype unknown_loc
     [([],"ml_translator_test_my_dep_type",
       [("My_dep",
         [Atapp []
            (Long "My_module2" (Short "ml_translator_test_my_type"))])])]]]”:
term
```
which is incorrectly using the long name `My_module2.ml_translator_test_my_type` since it should be `My_module.ml_translator_test_my_type`

**Comment by xrchz** [comment] 2018-11-21 15:55
Possibly a duplicate of #22

**Comment by oskarabrahamsson** [comment] 2018-11-26 16:10
I added this in 360f1b9 (which is on the [argparse](https://github.com/agomezl/cakeml/tree/argparse) branch)

**Closed by oskarabrahamsson** 2018-11-26 16:10 UTC
