### ISSUE TITLE
regression tests for the translator

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#64] opened 2015-08-21 23:06 UTC
This could be in the form of a theory (or theories) collecting various examples (like those found by @tanyongkiam)  that have cause the translator trouble in the past, stored in `translator/tests/`. I would then add them at the end of the `build-sequence`.

**Comment by myreen** [comment] 2015-08-22 15:11
I've created a file [translator/ml_translator_testScript.sml](https://github.com/CakeML/cakeml/blob/master/translator/ml_translator_testScript.sml) where regression tests should go. I put it in the main directory because this way it can use the same heap as the translator.

Once the regression tests start taking too long for normal builds, we might consider moving it into a subdirectory `translator/tests/`.

**Closed by myreen** 2015-08-22 15:11 UTC
