### ISSUE TITLE
better translator diagnostics

### ISSUE THREAD

**Issue by mn200** [CakeML/cakeml#530] opened 2018-09-28 06:20 UTC
When the translator complains about the lack of an induction principle, it prints out a message saying what to do interactively to get the right principle (use a `no_ind` variant), but it could also print out its own computation of exactly this missing induction principle.

**Comment by lorenzleutgeb** [comment] 2018-09-28 07:19
See https://github.com/CakeML/cakeml/blob/153ef4270fca8b5a3d6e9652f1f11edbad70406a/translator/ml_translatorLib.sml#L3607

**Comment by myreen** [comment] 2018-09-28 07:20
What do you mean by "its own computation of exactly this missing induction principle"? The computation is a complicated chain of ML code.

**Comment by mn200** [comment] 2018-10-01 12:02
If the code is in a position to suggest 
```
val res = translate_no_ind foo_def
g `^(first is_forall (hyp res))`
```
why can't it compute `res` itself (it has access to both the proposed definition, and to `translate_no_ind`, right?), extract its first universal hypothesis, and then show this to the user?

**Comment by myreen** [comment] 2018-10-01 12:08
Do you mean that it should pretty print a concrete term instead of producing the antiquotation? These can be very large and stating the term might make the proof brittle to minor changes in the translated definition.

However, if the user proves the induction theorem and stores it in the theory before calling `translate` then one might not even need to call `translate_no_ind`. Would this be preferred?

**Comment by mn200** [comment] 2018-10-02 00:10
It's only printing a diagnostic suggestion as to how to proceed (and should include the suggested antiquotation approach as well to encourage the user to take a more robust approach).  

I don't know what the best workflow should be on the part of the user once they have the information, but actually getting to see the term without having to interactively go through the pain of getting the translator into the right state (see #531) could be helpful.

**Comment by myreen** [comment] 2018-10-02 08:39
@mn200 OK, how about the following output for a fake case where the translator cannot prove the induction for list append? Note that the induction theorem even for list append is mostly unreadable due to excessive type annotations. I print the induction theorems with `show_types` set to `true`.

    Translating append
    
    ERROR: Unable to prove induction for listTheory.APPEND
    
    ∀(P0 :α list reln).
        (∀(l :α list). P0 ([] :α list) l) ∧
        (∀(t :α list). (∀(l :α list). P0 t l) ⇒ ∀(h :α) (l :α list). P0 (h::t) l) ⇒
        ∀(l :α list) (l' :α list). P0 l l'
    
      This induction goal has been left as an assumption
      on the theorem returned by the translator. You can
      prove it with something like the following before
      this constant is used in subsequent translations.
    
    val res = translate_no_ind listTheory.APPEND;
    
    val ind_lemma = Q.prove(
      `^(first is_forall (hyp res))`,
      rpt gen_tac
      \\ rpt (disch_then strip_assume_tac)
      \\ match_mp_tac (latest_ind ())
      \\ rpt strip_tac
      \\ last_x_assum match_mp_tac
      \\ rpt strip_tac
      \\ fs [FORALL_PROD])
      |> update_precondition;

      Here `translate_no_ind` does the same as `translate`
      except it does not attempt the induction proof.

      Alternatively, you can keep on using `translate` if
      you prove the induction goal from above and save is
      as listTheory.APPEND_ind.

**Comment by mn200** [comment] 2018-10-02 23:55
Sure, that looks great for the list case.  The choice to have type variables on is fine in this one, but if it more usually obscures than helps, then you could think about having `show_types` as false I suppose.

**Comment by myreen** [comment] 2018-10-03 08:01
I'll take that as an OK from @mn200. The change passed the relevant part of the regression test and have been merged. I will close this issue.

**Closed by myreen** 2018-10-03 08:01 UTC
