### ISSUE TITLE
parsingComputeLib doesn't build

### ISSUE THREAD

**Issue by formrre** [CakeML/cakeml#575] opened 2018-12-06 12:15 UTC
`parsingComputeLib` doesn't build under some very specific conditions anymore, Holmake in `compiler/parsing` fails with:
`Don't know how to build necessary target(s): /home/user/cakeml/semantics/semanticsComputeLib.ui`
This happened, because `semanticsComputeLib` was moved into `semantics/proofs`.
This can be potentially fixed by moving `parsingComputeLib` into `parsing/proofs`.
`Holmake -r cleanDeps` doesn't help and I am failing to reproduce this even on a fresh clone

**Comment by formrre** [comment] 2018-12-06 12:54
This must be attempted before doing `Holmake` inside `parsing/proofs` as they share the same heap.

**Comment by formrre** [comment] 2018-12-06 14:18
@xrchz concerning your comments on #576 the other possible fixes I can think of are making `parsing` depend on `semantics/proofs`, reverting to the state before `cleanup`, where `semanticsComputeLib` was in `semantics`, but that would move namespaceProps and termination back too, or just document the weird behaviour.

**Comment by mn200** [comment] 2018-12-07 04:12
What is the route to reproduction from a clean checkout of `master` please?

**Comment by formrre** [comment] 2018-12-07 08:11
@mn200 to reproduce the odd `load` behaviour do:
1. `Holmake` inside `compiler/parsing` on a clean checkout, it builds `semantics`, but not `semantics/proofs`, where the `semanticsComputeLib` currently is, doing `load "parsingComputeLib";` interactively afterwards fails.
2. if you do `Holmake` inside `semantics/proofs` on a clean checkout and then inside `compiler/parsing` everything works nicely.

This is because, `semantics` and `semantics/proofs` share a `heap`, if I understand correctly.
I have no idea how to reproduce the Holmake failure on  a clean checkout at the moment.

**Comment by xrchz** [comment] 2018-12-09 08:41
Is there also an option to remove the dependency?

I'm leaning towards option 1 otherwise, but I also see this as an opportunity to progress the observation in #321 that `parsingComputeLib` is not used where it ought to be.

**Comment by mn200** [comment] 2018-12-09 11:12
If there were a clear specification for what parsingComputeLib is supposed to do, your option 4 might be possible.  At a guess, I suppose it's supposed to provide `CBV_CONV`-ability for parser calls, but do “parser calls” include `cmlPtreeConversion` functionality, for example?  And who is the client for this? 

Once the spec is nailed down, it would then be fairly straightforward to assemble the list of rewrites/definitions that would have to go into it.  That needn't depend on `semantics` at all (any uses of `cmlPtreeConversion` functions could be explicitly handled in `compiler/parsing`).  

But again, as Makarius might say, what is the actual desired application? 

By the way, assembling computeLib lists of theorems in one place is a fragile methodology, as we see when theorems are deleted or replaced, and computeLib files then annoyingly break.  I think theorem attributes would handle this better.

**Comment by xrchz** [comment] 2018-12-09 11:20
The client is `parse_topdecs` or `process_topdecs` as mentioned in #321.

**Comment by mn200** [comment] 2018-12-19 01:16
parse_topdecs requires evaluation of functions defined in semantics (those from `ptreeConversion`). I can pull in the appropriate definitions trivially enough, making it not depend on semanticsComputeLib.  But then, that would seem to defeat the purpose of having a semanticsComputeLib.  (It's easy to not depend on things if you just avoid the abstractions they provide and build your own copies.)

**Comment by xrchz** [comment] 2018-12-19 12:08
Thanks for that info. We have now ruled out option 4, and I'd say we should also veto option 1 given the existence of `parse_topdecs`. Therefore, I suggest to take option 2: make `compiler/parsing` depend on `semantics/proofs`. (I said earlier why this isn't as bad as it looks: semantics are not like the implementation, and can all be considered `proofs`-like.)

**Comment by mn200** [comment] 2018-12-21 05:13
This makes me wonder if we shouldn't just merge `semantics` and `semantics/proofs`.

Holmake handles big directories better than successive small ones too (at least for the moment).

**Comment by mn200** [comment] 2018-12-21 05:16
Also: can you suggest/dictate a naming scheme for regression test files please?  I want to test `*computeLib` files (obviously, those in `semantics` and `parsing` have never been so tested) and to do it soon after they're set up.  Without a `selftest.exe` mechanism it seems easiest to just create a “test” theory to do this.

**Comment by myreen** [comment] 2018-12-21 05:17
Even if we merge parts, I hope we can retain the idea that:
 - `semantics` is the definition of the source semantics, and
 - `semantics/proofs` are proofs / general lemmas about the source semantics.

This is in line with how we separate the compiler definition from the compiler proofs.

**Comment by mn200** [comment] 2018-12-21 05:18
Something has been mis-characterised if a computeLib is needed in `semantics/proofs`.

**Comment by xrchz** [comment] 2018-12-21 08:15
> Also: can you suggest/dictate a naming scheme for regression test files please? I want to test `*computeLib` files (obviously, those in `semantics` and `parsing` have never been so tested) and to do it soon after they're set up. Without a `selftest.exe` mechanism it seems easiest to just create a “test” theory to do this.
> 
> I do this in a separate test directory for the PEG.

The precedents I know of are
- `compiler/parsing/tests/*TestsScript.sml` (as you mentioned)
- `compiler/inference/tests/*Script.sml`
- `translator/ml_translator_testScript.sml`
I think the `tests` directory with whatever theories you like in it is a good convention. If there's only one theory you can opt for the single `_testScript.sml` approach, but it doesn't scale as well in case someone wants to do more tests some day.

**Comment by xrchz** [comment] 2018-12-21 08:20
> Something has been mis-characterised if a computeLib is needed in `semantics/proofs`.

`semantics/proofs` defines new constants that need to be in a `computeLib`. For example, `namespaceProps$alistSub`. It also proves better equations for previously defined constants such as `nsSub_compute_thm`. I could perhaps be convinced that these things (there are a few more) should be moved back to `namespaceTheory` rather than `namespacePropsTheory`, and then the `semanticsComputeLib` could move up with them. How does that sound? (Would @SOwens object to this?)

**Comment by mn200** [comment] 2019-01-04 04:18
Nitpick acknowledged!  

We already have a `tokenUtils` in `semantics`; it seems to me that analogous names could be used for other theory-stems.  Of course, it would probably be better still if we could just put the utility functions into the source `.lem` files, but `lem` is such a pain to use...

**Comment by xrchz** [comment] 2019-05-09 12:38
What needs to be done to close this issue?

**Comment by mn200** [comment] 2019-05-13 08:54
As per 4d95a4936d39, all of the parsing process's selftests execute with the custom compsets from `parsingComputeLib`.  I think I need to make sure that `parse_topdecs` or whatever the cf entrypoint is called also uses this tech.

**Comment by xrchz** [comment] 2019-05-13 11:46
All the parsing stuff to be replaced is in `cfTacticsBaseLib.sml`, I believe.

**Comment by xrchz** [comment] 2024-12-09 12:47
Can we delete `parsingComputeLib` because it's not used anywhere?

**Comment by dnezam** [comment] 2024-12-14 11:36
Closing, since #1111 has been merged.

**Closed by dnezam** 2024-12-14 11:36 UTC
